development:
  data_url: https://hours.library.columbia.edu/wifi-density.json
  data_cache_duration: <%= 10.minutes %>

test:
  data_url: https://hours.library.columbia.edu/wifi-density.json
  data_cache_duration: <%= 1.second %>
